
spring:
  servlet:
    multipart:
      enabled: true
      maxFileSize: 200MB
      maxRequestSize: 200MB
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 0.2
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: yonsz_mysql_ABC123
    url: jdbc:mysql://192.168.3.66:3306/hotel_test?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    hikari:
      auto-commit: false