uploader:
  qiniu:
    accessKey: v5_lQrM1YGKoXwU57o_liL3zqUaI8_mAO8QRreZW
    secretKey: 7Z7HFnW1w_Usq3NZtjCYueA0TTN55S_k4atbpYqS
  cos:
    secretId: AKIDfeJuQUKx4652aRPx9HOjuANRUyFRawAG
    secretKey: 6kjUrSvBKKATXSaXS8eyf8QvGbieNOBo
  alioss:
    accessKey: LTAI4Fe9jJsr3NVrb9u84WwB
    accessKeySecret: FElr8ay5YjTe0ZubV0bhm52EVnvzQd
demo:
  editDisabled: false


spring:
  datasource:
    username: root
    password: veryreader_mysql_ABC123
    url: jdbc:mysql://veryreader.com:13306/d2p_pm?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true

